In [23]:
import numpy as np
from IPython.display import clear_output
import time

In [24]:
n=int(input("n değerini giriniz:"))

n değerini giriniz: 5


In [25]:
Parray=np.zeros((n,n))
Carray=np.zeros((n,n))
NowCollision=0
MinCollision=0

In [26]:
for i in range(0,n):
    Parray[i][np.random.randint(0,n,1)]=1

In [27]:
def FindNowCollision(Parray):
    collision =0
    for y in range(0,n):#her satır
        x=np.where(Parray[y]==1)[0]
        #-----------------------
        for j in range(0,n):#her satır
            if(y==j):
                continue
                                                    #sütun kontrolü
            if(Parray[j][x]==1):
                collision +=1
        #----------------------- 
        for j in range(1,n):
            if(y-j >= 0 and x-j >=0):
                if(Parray[y-j][x-j]==1):
                    collision +=1
            else:
                break
        #----------------------- 
        for j in range(1,n):
            if(y-j >= 0 and x+j <n):
                if(Parray[y-j][x+j]==1):
                    collision +=1
            else:
                break
        #-----------------------
        for j in range(1,n):
            if(y+j < n and x-j >=0):
                if(Parray[y+j][x-j]==1):
                    collision +=1
            else:
                break
        #-----------------------
        for j in range(1,n):
            if(y+j < n and x+j <n):
                if(Parray[y+j][x+j]==1):
                    collision +=1
            else:
                break   
    return collision

In [28]:
def Nswap(a,b,TempParray1):
    TempParray1[a[0],a[1]],TempParray1[b[0],b[1]]=TempParray1[b[0],b[1]],TempParray1[a[0],a[1]]

In [29]:
def findArrayCollision(Parray1):
    for y in range(0,n):
        for x in range(0,n):
            TempParray=np.zeros((n,n)) 
            TempParray=np.copy(Parray1)
            px=np.where(Parray1[y]==1)[0]
            Nswap([y,px],[y,x],TempParray)
            
            Carray[y][x]=FindNowCollision(TempParray)

In [30]:
def randomMin(Carray1):
    c=np.where(Carray1==Carray1.min())#min değerler dizisi
    a=np.random.randint(0,len(c[0]),1)#min değerlerden rastgele sütun seçimi
    b=[row[a] for row in c]
    return b

In [31]:
def swap(minn):
    c=np.where(Parray[minn[0]]==1)
    Parray[minn[0],c[1]],Parray[minn[0],minn[1]]=Parray[minn[0],minn[1]],Parray[minn[0],c[1]]

In [32]:
def step(NCollision,MCollision):
    clear_output(wait=True)
    
    NCollision=MCollision
    print(f"Collision: {NCollision}")
    
    swap(randomMin(Carray))
     
    findArrayCollision(Parray)
    minn=randomMin(Carray)
    MCollision=int(Carray[minn[0],minn[1]])
    
    print(Carray)
    print()
    print(Parray)  
    return NCollision,MCollision

In [33]:
NowCollision = FindNowCollision(Parray)
print(f"Collision: {NowCollision}") 
findArrayCollision(Parray)
minC=randomMin(Carray)
MinCollision=int(Carray[minC[0],minC[1]])
print(Carray)
print()
print(Parray)
time.sleep(1)



for i in range(0,300):# omuza gelince maximum kaç kez deneyecek 
    while(NowCollision>MinCollision):
        i=0
        
        NowCollision,MinCollision=step(NowCollision,MinCollision)
        #time.sleep(1)
        if(NowCollision==0): 
            break
            
    if(NowCollision==0): 
        break       
    NowCollision,MinCollision=step(NowCollision,MinCollision)
    #time.sleep(1)
    print(f"shoulder iteration: {i}")
    
        

Collision: 0
[[4. 4. 4. 4. 0.]
 [2. 0. 6. 4. 4.]
 [6. 4. 6. 0. 4.]
 [0. 6. 4. 6. 4.]
 [4. 6. 0. 2. 4.]]

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# 